### ISSUE TITLE
enable ssl

### ISSUE THREAD

**Issue by kylemcdonald** [kylemcdonald/wifiwhisperer#3]
* A certificate from Let’s Encrypt was installed, and will expire in August.
* The private key and certificate are located at:
    * /etc/letsencrypt/live/wifiwhisperer.com/privkey.pem
    * /etc/letsencrypt/live/wifiwhisperer.com/cert.pem
* There is an example of using these keys with Express in `/root/encrypt-test/app.js`
* We shouldn’t be too worried about the security of these keys since obtaining them would only mean that someone could perform a MITM attack on wifiwhisperer.com, so feel free to make copies, but don’t put them on GitHub.
* It might be best to add an environment variable that has the root location for these certificates, to make local development easier.

@dyleeo or @jedahan want to take a stab at plugging this into `wifiwhisperer/index.js`?

**Comment by dyleeo** [comment]
I will give this a try. Thanks for setting up the SSL, Kyle.

**Comment by dyleeo** [comment]
HTTPS and HTTP redirect are working on production server.

**Comment by kylemcdonald** [comment]
thanks!
